tests: Make run_image_tests.sh fail on ls errors. Fix #1002
osbuild/osbuild-composer pull request #1003
Opened 2020-09-22 15:12 UTC by atodorov

man set says:

... The shell does not exit if the command that fails is part
of  the  command list  immediately  following a while or until
keyword ...

It doesn't say anything about `for` but it looks like it's the
same.

2020-09-23 09:17 UTC, ondrejbudai commented
This doesn't make the tests fail. The other issue is in the command substitution. See https://stackoverflow.com/questions/58859554/how-to-use-set-e-inside-a-bash-command-substitution

2020-09-23 09:17 UTC, ondrejbudai requested changes
This doesn't make the tests fail. The other issue is in the command substitution. See https://stackoverflow.com/questions/58859554/how-to-use-set-e-inside-a-bash-command-substitution

2020-09-23 11:01 UTC, atodorov commented
> This doesn't make the tests fail.

Right. When I tested it locally with a simplified version of this script I got a non-zero exit code but not in Jenkins. Not sure why. Here's my test script for reference:

```
#/bin/bash
set -euo pipefail

get_test_cases () {
    ls /tmp/non-existing
}

CASES=$(get_test_cases)
for TEST_CASE in $CASES; do
    echo "Running $TEST_CASE"
done
```

> The other issue is in the command substitution. See https://stackoverflow.com/questions/58859554/how-to-use-set-e-inside-a-bash-command-substitution

I see lots of info here, not sure what are you pointing me at exactly.

2020-09-24 23:54 UTC, teg approved these changes
Looks good.

2020-09-25 12:08 UTC, atodorov commented
> Looks good.

I can't merge with failing checks. #1005 fixes the failures exposed here. The ostree test failure is unrelated.

2020-09-29 07:46 UTC, ondrejbudai commented
Superseded by #1005

2020-09-29 07:46 UTC, closed without merging