add more logging to the worker
osbuild/osbuild-composer pull request #1093
Opened 2020-11-19 16:14 UTC by ondrejbudai

wip

2020-11-23 19:50 UTC, larskarlitski requested changes
I like this and I agree with your reasoning that buffering is fine. Manifests need to fit into memory anyway, because osbuild loads them, too.

However, I think you accidentally added an extraneous file `register.sh`.

2020-11-23 19:55 UTC, ondrejbudai commented
indeed, fixed, thanks!

2020-11-23 20:02 UTC, larskarlitski approved these changes
Thank you!

2020-11-25 07:37 UTC, teg approved these changes

2020-11-25 07:37 UTC, merged