schutzbuild: enable mockbuild on aarch64
osbuild/osbuild-composer pull request #1110
Opened 2020-11-25 14:51 UTC by ondrejbudai

![image](https://user-images.githubusercontent.com/119861/100243281-fda2a900-2f35-11eb-81dc-5bbcb690c97b.png)

2020-11-26 12:52 UTC, larskarlitski submitted a review, later dismissed
Thanks! Looks correct to me.

2020-11-30 13:00 UTC, msehnout requested changes
Looks very nice! CI is unhappy because of unbound variables, but that is easy to fix.

2020-11-30 15:15 UTC, ondrejbudai commented on schutzbot/Jenkinsfile
> +                        AWS_IMAGE_TEST_CREDS = credentials('aws-credentials-osbuild-image-test')
Thanks, fixed!

2020-11-30 16:56 UTC, teg approved these changes

2020-12-01 07:27 UTC, msehnout approved these changes
Very nice!

2020-12-01 07:27 UTC, merged