distro/rhel84: use the org.osbuild.rhel84 runner
osbuild/osbuild-composer pull request #1125
Opened 2020-12-01 18:02 UTC by gicmo

The RHEL 8.4 specific runner was introduced in osbuild 22, released on the 8th of October 2020. It should by now be in relevant Fedora releases and RHEL 8.4.

2020-12-01 18:46 UTC, ondrejbudai approved these changes
Thanks! (osbuild-composer already requires `osbuild >= 23`)

2020-12-01 20:09 UTC, jkozol approved these changes
Great! Thanks!

2020-12-02 07:42 UTC, ondrejbudai requested changes
Ah, you need to do the same change in the testing manifests: `test/data/manifests/rhel_84*`

2020-12-04 18:20 UTC, jkozol approved these changes
LGTM! Thanks!

2020-12-04 18:28 UTC, ondrejbudai approved these changes

2020-12-04 18:28 UTC, merged