distro/rhel84: remove rng-tools
osbuild/osbuild-composer pull request #1127
Opened 2020-12-04 22:35 UTC by jkozol

rng-tools is no longer included as a package in the RHEL 8.4 image. This package is both removed from being an included package and also specifically declared as excluded. The test manifests are updated.

I am unsure why rng-tools needs to be explicitly declared as excluded. But, when I just removed it from the included packages list, it was still getting added to the manifest. I tried running `dnf repoquery --whatdepends` to see what might be pulling it in but that didn't reveal anything. If anyone has thoughts on this I'd appreciate the info.

2020-12-07 09:35 UTC, ondrejbudai requested changes
Thanks! The image tests don't like the changes though. Weird... Ping me if you need help investigating. :)

2020-12-08 02:12 UTC, jkozol commented
The manifests seemed to have dropped too many packages. I regenerated them and they seem to be fixed. I wasn't able to replicate the manifests generating incorrectly so I'm not sure what went wrong.

2020-12-08 13:03 UTC, ondrejbudai approved these changes
Looks good to me, thanks!

2020-12-08 13:04 UTC, ondrejbudai commented
openstack image test failed because of PSI Openstack outage, this is a known issue.

2020-12-08 13:04 UTC, merged