distro/rhel84: use New York as default timezone
osbuild/osbuild-composer pull request #1152
Opened 2021-01-08 17:58 UTC by jkozol

RHEl 8.4 guest images need to have the default time zone of EST/EDT unless the user specifies one in their blueprint. New York is a major location for this time zone.

2021-01-08 18:24 UTC, ondrejbudai approved these changes
Thanks!

(I wanted to spice up the approval with a New York meme but I failed to find a good one.)

2021-01-09 13:39 UTC, teg approved these changes

2021-01-11 09:04 UTC, ondrejbudai requested changes
Image tests are failing because of this change.

2021-01-13 16:20 UTC, jkozol commented
@ondrejbudai Tests are now passing. Could I get a rereview? Thanks!

2021-01-13 16:49 UTC, ondrejbudai approved these changes
Awesome, thanks!

2021-01-13 16:49 UTC, merged