Main compose packagesets
osbuild/osbuild-composer pull request #1299
Opened 2021-03-15 23:55 UTC by bcl

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change
- [ ] PR contains automated tests for new functionality and

2021-03-16 08:18 UTC, ondrejbudai commented
This PR modified the signature of `Store.PushCompose()` but did not modify the calls, therefore the tests are failing.

I think we also need to add `PackageSets` to `internal/store/json.go` so the package sets are persistent.

2021-03-22 18:21 UTC, teg requested changes
I really like this! Just one suggestion for changes inline.

2021-03-22 18:21 UTC, teg commented on internal/weldr/api.go
> +		dependencies := compose.PackageSets["packages"]
Could we just store the `packages` PackageSet in the store? That way we don't make the names of the sets API, and we would also avoid storing the build-root packages etc which we currently have no use for / way to export.

2021-03-22 18:21 UTC, teg commented on cmd/osbuild-store-dump/main.go
> +	manifest, packageSpecSets = getManifest(bp1, t2, a, d, rpmmd, repos)
Could you explain the context a bit in the commit message? :)

2021-03-22 18:21 UTC, teg commented on internal/store/json.go
> +	PackageSets map[string][]rpmmd.PackageSpec `json:"package_sets"`
As suggested elsewhere: should we make this only be the `packages` set, so we don't make the names of the sets API, nor the build-root++

2021-03-24 10:25 UTC, teg approved these changes
Nice! Thanks!

2021-03-29 07:56 UTC, ondrejbudai approved these changes

2021-03-29 18:08 UTC, bcl commented
@teg Can this be merged? I don't see why Schutzbot says failed, everything looks green on the details page.

2021-03-29 23:19 UTC, teg commented
Base tests timed out on aarch64 EL8. This is caused by `qemu-img` hanging, not related to this PR.

2021-03-29 23:19 UTC, merged