Add Google Compute Engine image type
osbuild/osbuild-composer pull request #1365
Opened 2021-04-19 12:21 UTC by thozza

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
  - [x] unit tests were updated to incorporate the new image type
  - [x] `api.sh` test case was updated to use the new image type
  - [ ] new image test case for the image type has been generated (**TODO**, blocked on https://github.com/osbuild/rpmrepo/pull/3)
- [ ] adequate documentation informing people about the change such as
  - [x] image type documentation for GCP has been added
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news (**TODO**)
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

Add `gce-byos` image type for use with Google Cloud Platform, into RHEL-8.3 and RHEL-8.4 distro. The image is available only for x86_64 architecture, as the only one supported by GCP. "byos" in the name stands for "Bring Your Own Subscription", which is consistent with how Google names such image and it means that users must use subscription-manager to get RHEL content. The image is loosely based on the RHEL Guest image provided by Google in their marketplace, because Google does quite a lot of tweaks to the image, which are currently not possible with osbuild. Main benefit of the image type is that it uses proper kernel arguments to work with GCE serial and availability of the Google guest tools and SDK on the image.

Add documentation about the GCE image type into `image-types/rhel8/`. It contains detailed information from the research of Google's RHEL Guest image as well as description of mechanisms available to import images to GCP.

Add repository definition with Google Guest tools and use it in the Cloud API test case.

Modify the Cloud API test case to use the new `gce-byos` image type and also to use the proper repository with Google Guest tools as part of the compose request.

2021-04-20 07:42 UTC, atodorov approved these changes
lgtm

2021-04-21 15:26 UTC, thozza commented
The PR should be ready for review. The GCE Image is content-wise as close as possible to what Google provides in their marketplace. Image test cases have been generated for the new image type on all RHEL and CentOS distros.

2021-04-23 08:04 UTC, ondrejbudai commented
Hmm, is the new image type exposed in the Weldr API? I think it is because we expose all of them. I'm not sure though if it's buildable using the Weldr API because it doesn't have the google repository available.

2021-04-23 10:07 UTC, thozza commented
> Hmm, is the new image type exposed in the Weldr API? I think it is because we expose all of them. I'm not sure though if it's buildable using the Weldr API because it doesn't have the google repository available.

Thanks for pointing this out Ondrej. I didn't test Weldr without having explicit support for uploading to GCP, but if it automatically supports building all types of images, I'll have to test it.  I have the a PoC ready on a different branch, including the upload, so it should not be a problem to pick relevant changes to this PR.

I'll mark this PR as a Draft in the meantime...

2021-04-26 17:13 UTC, thozza commented
PR is ready for review / comments. I ended up adding full support into Weldr API for GCP, including uploading of the image...

2021-04-27 22:05 UTC, bcl requested changes
I think it would be better to make this more generic, driven off the image names (assuming that each provider gets their own image type). That removes the need to have weldr know anything about providers, it becomes an extra set of image specific repos to be added to the depsolve.
Which also makes it easier to add support for other providers -- you just add a new image type and repository.

I'm not quite sure about repo file naming, it might be worthwhile to add a new directory of repos for image related repositories. But I'm not sure.

2021-04-27 22:05 UTC, bcl commented on cmd/osbuild-composer/composer.go
> +	// Load provider-specific repositories based on available image types
Make this generic, based on the image name so that it doesn't need to do gcp specific tests and name mangling.

2021-04-28 07:50 UTC, thozza commented on internal/weldr/api.go
> +	providerRepos map[string][]rpmmd.RepoConfig // Repositories specific for a given cloud provider
Each cloud provider will have almost certainly more than one image type. My reasoning was that the provider has a repository specific to a distribution, but not to each image type.

2021-04-28 07:54 UTC, thozza commented on internal/weldr/api.go
> +	for _, providerRepos := range api.providerRepos {
From my point of view these repositories are "system repositories" and they are used for depsolving and content that goes into the image. I don't see a reason to hide this from users. Why do we then display distribution repositories to them? Please help me understand why do you want to make a distinction here.

2021-04-28 07:55 UTC, thozza commented on internal/weldr/api.go
> +		for _, providerRepos := range api.providerRepos {
Please provide more specific reasoning why you propose to not treat it like a source, similar to how system repositories are treated.

2021-04-28 08:00 UTC, thozza commented on internal/weldr/api.go
> +			repo := func(name string) *store.SourceConfig {
No, it does not need to be a function, but the only other way how to break out of two for loops in Go would be to use labels and goto. Using an anonymous function makes it possible to easily return from it. Anonymous functions are used in a similar fashion in other parts of composer. I understand your preference, but in this case I would argue that the code is so short, that it is readable.

2021-04-28 08:02 UTC, thozza commented on internal/weldr/api.go
> +func (api *API) providerReposForImageType(imageType distro.ImageType) ([]rpmmd.RepoConfig, error) {
Thanks for your suggestion, but I don't see how using just the name instead of defined interface type makes it more generic.

2021-04-28 10:48 UTC, thozza commented
Thanks for your review and comments @bcl

> I think it would be better to make this more generic, driven off the image names (assuming that each provider gets their own image type). That removes the need to have weldr know anything about providers, it becomes an extra set of image specific repos to be added to the depsolve.

I agree that defining additional repositories per image type is a valid approach to the problem. It will give us more flexibility in the future if we need it, but as a result it will make us define more repo definitions even if their content is the same for all image types. 

I'll let the rest of the team comment on this approach before changing the implementation.

> Which also makes it easier to add support for other providers -- you just add a new image type and repository.

The "easiness" is subjective. It will make it a bit harder at the same time, as adding a new image type for the same cloud provider will require also adding new set of repositories. Not a problem from my PoV, just wanted to call this out.

> I'm not quite sure about repo file naming, it might be worthwhile to add a new directory of repos for image related repositories. But I'm not sure.

If the conclusion will be to define additional repositories per image type and not cloud provider, I would say that naming files `<distro-name>-<image-type-name>.json` should be reasonably OK.

As for the additional directory, I don't see a need at the moment to distinguish the distribution repo definitions and these additional image type/provider definitions by placing them into a separate directory. This may make things harder if the user decides to override the definition in `/etc/osbuild-composer/repositories/`, because they would have to create additional directory in it. Having all definitions in the same directory has also its potential advantages like the ability to list all distro repositories using `ls <distro-name>*.json`. But all in all, these reasons are all pretty subjective and I feel that the most neutral thing to do is to not introduce a separate directory at this moment. But I don't have a strong preference.

2021-08-10 09:43 UTC, thozza commented
This work will need to be completely refactored to v2 manifests and to produce a GCE image, which can be imported directly into GCP. Closing...

2021-08-10 09:43 UTC, closed without merging