test/cases: Introduce common "regression" test for all distros
osbuild/osbuild-composer pull request #1406
Opened 2021-05-11 13:19 UTC by msehnout

Create an entry point for all regression test called "regression.sh" and
run it as part of integration tests for all our distros. This entry
point contains logic for running only the test cases that are
appropriate for a given distribution.

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2021-05-12 07:57 UTC, atodorov commented on schutzbot/Jenkinsfile
> +
Doesn't matter much in which group this script is executed but ATM the integration group is rather big so you may leave this under the base group.

2021-05-12 07:59 UTC, atodorov commented on test/cases/regression-include-excluded-packages.sh
> +/usr/libexec/osbuild-composer-test/provision.sh
Won't that conflict/fail b/c regression.sh also calls provision.sh ? I can see for example:
```
sudo systemctl start osbuild-remote-worker.socket
sudo systemctl start osbuild-composer.socket
sudo systemctl start osbuild-composer-api.socket
```

which should probably be a restart or an if condition should be placed in provision.sh.

2021-05-13 10:13 UTC, atodorov requested changes

2021-05-13 10:13 UTC, atodorov commented on schutzbot/Jenkinsfile
> +        )
We're in the process of deprecating Jenkins. Also add the script to .gitlab-ci.yml Base section.

2021-05-20 09:04 UTC, msehnout commented
I've rebased the commit on top of the latest main and made the regression script part of Gitlab CI as well. Is it ok now, @atodorov ?

2021-05-20 10:06 UTC, atodorov approved these changes
LGTM.

2021-05-20 10:07 UTC, merged