test/regression: Start composer on rhel-like systems
osbuild/osbuild-composer pull request #1419
Opened 2021-05-24 08:52 UTC by msehnout

Reported here: https://github.com/osbuild/osbuild-composer/issues/1411

My plan:
 * read the `ID_LIKE` field in `/etc/os-release`
 * use the same code path as we use for CentOS

Missing pieces:
 * osbuild runner
 * configurable uefi vendor string
 * every RHEL clone needs to patch their RPM to contain their own repository URLs

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2021-05-31 13:25 UTC, atodorov commented on test/cases/regression-start-on-rhel-like-systems.sh
> +fi
Missing newline at EOF. Otherwise looks good to me.

2021-06-05 19:06 UTC, ondrejbudai requested changes
Thanks for looking into this! I'm afraid that the current implementation is racy. The backup is restored before composer even starts. I think you should run `composer-cli status` to check the composer's status.

Here's a snippet from the log explaining everything what happens there:

```
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal sudo[64750]:   centos : TTY=unknown ; PWD=/home/centos/~/builds/osbuild/ci/osbuild-composer ; USER=root ; COMMAND=/bin/systemctl restart osbuild-composer
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal sudo[64750]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal sudo[64750]: pam_unix(sudo:session): session opened for user root by (uid=0)
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal systemd[1]: Stopping OSBuild Composer...
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal osbuild-worker[51219]: 2021/05/24 09:40:19 error requesting job: Post "http://localhost/api/worker/v1/jobs": EOF
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal systemd[1]: osbuild-composer.service: Succeeded.
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal systemd[1]: Stopped OSBuild Composer.
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal systemd[1]: Started OSBuild Composer.
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal sudo[64750]: pam_unix(sudo:session): session closed for user root
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal systemd[1]: osbuild-worker@1.service: Main process exited, code=exited, status=1/FAILURE
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal systemd[1]: osbuild-worker@1.service: Failed with result 'exit-code'.
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal sudo[64760]:   centos : TTY=unknown ; PWD=/home/centos/~/builds/osbuild/ci/osbuild-composer ; USER=root ; COMMAND=/bin/mv /etc/os-release.backup /etc/os-release
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal sudo[64760]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal sudo[64760]: pam_unix(sudo:session): session opened for user root by (uid=0)
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal sudo[64760]: pam_unix(sudo:session): session closed for user root
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal osbuild-composer[64754]: 2021/05/24 09:40:19 Loaded configuration:
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal osbuild-composer[64754]: [koji]
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal osbuild-composer[64754]:   allowed_domains = ["localhost", "client.osbuild.org"]
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal osbuild-composer[64754]:   ca = "/etc/osbuild-composer/ca-crt.pem"
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal osbuild-composer[64754]: [worker]
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal osbuild-composer[64754]:   allowed_domains = ["localhost", "worker.osbuild.org"]
kvě 24 09:40:19 ip-172-31-69-141.ec2.internal osbuild-composer[64754]:   ca = "/etc/osbuild-composer/ca-crt.pem"
```

2021-06-07 08:05 UTC, msehnout commented
> Thanks for looking into this! I'm afraid that the current implementation is racy. The backup is restored before composer even starts. I think you should run `composer-cli status` to check the composer's status.
> 
> Here's a snippet from the log explaining everything what happens there:
> 
> ```
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal sudo[64750]:   centos : TTY=unknown ; PWD=/home/centos/~/builds/osbuild/ci/osbuild-composer ; USER=root ; COMMAND=/bin/systemctl restart osbuild-composer
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal sudo[64750]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal sudo[64750]: pam_unix(sudo:session): session opened for user root by (uid=0)
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal systemd[1]: Stopping OSBuild Composer...
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal osbuild-worker[51219]: 2021/05/24 09:40:19 error requesting job: Post "http://localhost/api/worker/v1/jobs": EOF
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal systemd[1]: osbuild-composer.service: Succeeded.
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal systemd[1]: Stopped OSBuild Composer.
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal systemd[1]: Started OSBuild Composer.
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal sudo[64750]: pam_unix(sudo:session): session closed for user root
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal systemd[1]: osbuild-worker@1.service: Main process exited, code=exited, status=1/FAILURE
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal systemd[1]: osbuild-worker@1.service: Failed with result 'exit-code'.
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal sudo[64760]:   centos : TTY=unknown ; PWD=/home/centos/~/builds/osbuild/ci/osbuild-composer ; USER=root ; COMMAND=/bin/mv /etc/os-release.backup /etc/os-release
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal sudo[64760]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal sudo[64760]: pam_unix(sudo:session): session opened for user root by (uid=0)
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal sudo[64760]: pam_unix(sudo:session): session closed for user root
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal osbuild-composer[64754]: 2021/05/24 09:40:19 Loaded configuration:
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal osbuild-composer[64754]: [koji]
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal osbuild-composer[64754]:   allowed_domains = ["localhost", "client.osbuild.org"]
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal osbuild-composer[64754]:   ca = "/etc/osbuild-composer/ca-crt.pem"
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal osbuild-composer[64754]: [worker]
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal osbuild-composer[64754]:   allowed_domains = ["localhost", "worker.osbuild.org"]
> kvě 24 09:40:19 ip-172-31-69-141.ec2.internal osbuild-composer[64754]:   ca = "/etc/osbuild-composer/ca-crt.pem"
> ```

lol, good catch, thanks for looking into this :-)

2021-07-19 13:17 UTC, msehnout commented
Closing for now, we can reconsider if anyone starts implementing this: https://github.com/osbuild/osbuild-composer/issues/1411

2021-07-19 13:17 UTC, closed without merging