prometheus: collect metrics from cloudapi
osbuild/osbuild-composer pull request #1455
Opened 2021-06-09 17:33 UTC by chloenayon

Create prometheus package to provide infrastructure to gather metrics. Implement it 
in cloudapi and worker to collect information including number of total and successful 
compose requests. 

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2021-06-10 11:09 UTC, Gundersanne requested changes
Looking good, two items:

The ComposeSuccesses need some work.

And for testing we could call `/metrics` before and after a compose in the api test (and maybe koji?), and then make sure the relevant metrics increased?

2021-06-15 09:17 UTC, Gundersanne reviewed
So small linting error https://github.com/osbuild/osbuild-composer/pull/1455/checks?check_run_id=2797485029

2021-06-15 09:17 UTC, Gundersanne commented on osbuild-composer.spec
> +%systemd_post osbuild-composer.service osbuild-composer.socket osbuild-composer-api.socket osbuild-remote-worker.socket
Trailing whitespace, here and below

2021-06-23 09:01 UTC, Gundersanne requested changes
Thank you! The test needs some fixes but the placement and idea are correct.

2021-06-23 20:28 UTC, chloenayon commented on test/cases/api.sh
> +METRICS_LINE=$(echo "$METRICS_OUTPUT" | grep "^total_compose_requests")
Thank you for this especially, I was having trouble coming up with a way to get the number in one line

2021-07-01 09:21 UTC, Gundersanne commented
Hmm in the api test it tries calling metrics `curl --cacert ca-crt.pem --key client-key.pem --cert client-crt.pem https://localhost/metrics` but the credentials aren't entirely correct.

`curl --silent --show-error --cacert /etc/osbuild-composer/ca-crt.pem --key /etc/osbuild-composer/client-key.pem --cert /etc/osbuild-composer/client-crt.pem --header 'Content-Type: application/json' --request POST --data @/tmp/tmp.3pvnqah8Lh/request.json https://localhost/api/composer/v1/compose` is the compose request, they have absolute paths towards the ca/key/cert.

2021-07-02 17:31 UTC, Gundersanne commented on test/cases/api.sh
> +PREV_COMPOSES=$(echo "$METRICS_OUTPUT" | grep "^total_compose_requests" | cut -f2 -d' ')
As the first `/metrics` curl happens after the first `/compose` request, the `total_compose_requests` is already 1; so the test later on will fail as `$((PREV_COMPOSES + 1))` is 2.

So just move the first /`metrics` call to before the first `/compose` call and you should be good. Mind if you also check the `"^total_successful_compose_requests"` ? Just for completeness, check it in the same way as PREV_COMPOSES, but then like PREV_SUCCESSFUL_COMPOSES or something.

2021-07-20 10:36 UTC, Gundersanne commented on test/cases/api.sh
> +    "$1"="$(echo "$METRICS_OUTPUT" | grep "^total_compose_requests" | cut -f2 -d' ')"
Bash functions are a little quirky, they return whatever gets written to stdout in that function. It is possible to do what you're doing here using `declare -n out="$1"` and then `out="whatever value"` but I'm not super familiar with `declare`.

```
function barme () {
    declare -n out=$1
    out="bar"
}

FOO="foo"
declare -n FOO
barme FOO
echo $FOO # == bar
``` 

But this is difficult to read I think. Just using stdout will make a lot more sense to most people.

```
function collectMetrics() {
...
echo "$METRICS_OUTPUT" |  ... |cut -f2 -d' '
}
COMPOSES="$(collectMetrics)"
# or just
test "$(collectMetrics)" = "1"
```

2021-07-23 10:38 UTC, Gundersanne approved these changes
thanks!

2021-07-23 19:54 UTC, merged