Add .gitleaks.toml
osbuild/osbuild-composer pull request #1562
Opened 2021-07-16 12:46 UTC by bplaxco

I'd like to add this to help a few scanners avoid false positives. If you have an guidance on how to tune that config so that it doesn't ignore a real leak, just let me know and I can make the necessary changes. 

This pull request includes:

- [X] adequate testing for the new functionality or fixed issue
- [X] adequate documentation informing people about the change such as
  - [X] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news (no need to mention in release)
  - [X] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/ (no behavior was changed)

2021-07-19 09:08 UTC, ondrejbudai commented
Hi! I wonder how this is beneficial to our project? In case of a leak, will you notify us? How? It feels to me that I need more information about this project until I can review this PR. Thanks! :)

2021-07-19 09:19 UTC, atodorov requested changes
You need to enable the gitleaks GitHub Action at least. Otherwise the config file by itself is useless.

2021-07-19 09:20 UTC, atodorov commented
@ondrejbudai checkout https://github.com/zricethezav/gitleaks and https://gamma.ai/github-demo for more context.

2021-07-21 12:13 UTC, bplaxco commented
> Hi! I wonder how this is beneficial to our project? In case of a leak, will you notify us? How? It feels to me that I need more information about this project until I can review this PR. Thanks! :)

Yep we'll notify you. I'll follow up in work chat. 

> You need to enable the gitleaks GitHub Action at least. Otherwise the config file by itself is useless.
There's an external scanner :)

2021-07-30 12:48 UTC, bplaxco commented
After a discussion with @ondrejbudai, I'm going to go ahead and kill this so things can be handled on a case by case basis as alerts are raised ^_^

2021-07-30 12:48 UTC, closed without merging