cloudapi: change Organization customization to a string
osbuild/osbuild-composer pull request #1641
Opened 2021-08-12 10:55 UTC by chloenayon

Make Organization in the Subscription customization a string
instead of an int.

fixes #1582 

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2021-08-18 18:24 UTC, Gundersanne requested changes
Ah nice, good catch in the distro package, I didn't realize this issue went all the way into there.

Still needs a change in `test/cases/api.sh`; when building the request the organization value needs some quotes around it.

2021-08-22 12:07 UTC, gicmo commented
This needs a rebase on main to fix CI

2021-08-31 13:24 UTC, Gundersanne approved these changes
Very nice, thanks!

edit: just re-triggered CI.

2021-09-01 09:27 UTC, Gundersanne requested changes
Sorry for doing this, but I think it's better to not break the openapi.yml, but keep the internal change to string of SubscriptionImageOptions.

After reconsidering this and introducing v2 soon in #1704, let's not give ourselves the headache of having to updating image-builder at the same time.

And then in server.go:
```
- Organization:  request.Customizations.Subscription.Organization,
+ Organization:  fmt.Sprintf("%d", request.Customizations.Subscription.Organization),
```

Sorry for the double work, my bad as I said something different in the issue :(

2021-09-01 09:27 UTC, Gundersanne commented on internal/cloudapi/openapi.yml
> +          example: '2040324'
let's revert this to an intereger

2021-09-01 09:27 UTC, Gundersanne commented on test/cases/api.sh
> +      "organization": "${API_TEST_SUBSCRIPTION_ORG_ID:-}",
This can also be reverted.

2021-09-08 15:10 UTC, Gundersanne approved these changes
lgtm!

2021-09-08 15:38 UTC, merged