Submount fix
osbuild/osbuild-composer pull request #1715
Opened 2021-08-31 17:40 UTC by kingsleyzissou

This pull request includes:

Currently the filesystem configuration allows for mount points and their direct sub-directories to be configured as separate partitions (i.e. `/var` & `/var/log`). This pr expands this support to add an additional level to allow for grandchild-directories (i.e. `/var/log/audit`)
 

- [x] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2021-09-01 08:54 UTC, ondrejbudai commented
I wonder if we should allow arbitrary depth. Do we foresee any issues if we do that? cc @teg

2021-09-01 10:55 UTC, kingsleyzissou commented
@ondrejbudai good point, that would probably scale a lot better. Will wait to see what @teg suggests

2021-09-01 12:22 UTC, teg commented
Agreed, let's lift the limitation on depths. Really what we want to limit is the top-level mounts, what people do under the ones we allow we don't care about.

2021-09-01 12:41 UTC, teg requested changes
We need to discuss whether rot land this for 8.5/9.0, but otherwise: great stuff!

2021-09-08 17:58 UTC, ondrejbudai approved these changes

2021-09-15 08:46 UTC, ondrejbudai approved these changes
Exception granted for both distros, merging.

2021-09-15 08:46 UTC, merged