schutzbot: run openstack/* jobs on a dedicated runner
osbuild/osbuild-composer pull request #1732
Opened 2021-09-03 08:18 UTC by ondrejbudai

We have limited resources in openstack. We can only run about 40 concurrent VMs.
Previously, the rate limiting was kinda stupid:

All (aws and openstack) jobs were run using the same runner. This runner was
globally limited to 60 concurrent jobs. For openstack, the individual
images were also limited to a certain number of concurrent jobs in
the gitlab-ci-terraform repository so we don't hit the quota. This limit
was applied at runtime - the first thing that an openstack job did was to
wait for a slot. This job counted towards the global limit of jobs (60)
and thus was blocking one slot without doing any useful work.

Applying local limits to please global quota is stupid though. We have much
more demand for rhel-8.5 runner than for e.g. Fedora. It would be much
better to just use global limit that would map much nicely to global
quota.

Today, I've introduced a new runner with tag terraform/openstack. It's
currently limited to 20 concurrent jobs. All jobs running on openstack should
run on the new runner. This runner has the local rate limiting for openstack
disabled. This means that we can run 20 concurrent openstack jobs and it
doesn't matter which distribution they run.

To sum it up, this has two benefits:
- no local limits, we can just use the full quota
- no idling jobs waiting for an openstack slot

Note that the openstack global limit is currently set to 20, I will raise
it once all PRs are rebased on top of this change.

Side effect: I moved all libvirt test to openstack. I think this is overall
better because testing guest images on KVM makes more sense than testing them
on TCG.

Signed-off-by: Ondřej Budai <ondrej@budai.cz>

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2021-09-03 11:52 UTC, Gundersanne submitted a review, later dismissed

2021-09-04 08:06 UTC, ondrejbudai commented
Force-pushed to fix a conflict.

2021-09-04 10:58 UTC, Gundersanne submitted a review, later dismissed

2021-09-04 11:14 UTC, Gundersanne requested changes
needs another source-prepare

2021-09-04 11:37 UTC, ondrejbudai commented
Yeah, I will rebase it as soon as I come home.

2021-09-04 17:42 UTC, ondrejbudai commented
Rebased.

2021-09-04 18:59 UTC, Gundersanne approved these changes

2021-09-04 21:14 UTC, merged