RHEL-8.5/9.0: keep RHSM DNF plugins enabled on `ec2`, `ec2-ha` and `ami`
osbuild/osbuild-composer pull request #1733
Opened 2021-09-03 13:01 UTC by thozza

The RHSM DNF plugins `product-id` and `subscription-manager` are now
by default enabled on the RHEL-8.5 and RHEL-9.0 `ec2`, `ec2-ha` and
`ami` images.

The desired default state of the RHSM DNF plugins has been decided by
the RHSM team.

Related to https://bugzilla.redhat.com/show_bug.cgi?id=1996670

Signed-off-by: Tomas Hozza <thozza@redhat.com>

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2021-09-06 14:15 UTC, thozza commented
The CI pipeline was for some reason canceled, I re-scheduled it.

2021-09-06 16:21 UTC, ondrejbudai requested changes
Looks good, although I'm blocking it until we get the exception.

2021-09-10 19:28 UTC, thozza commented
@ondrejbudai this one should be unblocked, since the exception has been granted....

2021-09-14 09:47 UTC, ondrejbudai approved these changes

2021-09-14 09:47 UTC, merged