rhel85: set bootloader to `none` for edge raw images
osbuild/osbuild-composer pull request #1759
Opened 2021-09-09 09:45 UTC by gicmo

Use the new bootloader config for OSTree deployments to set the bootloader backend to `none` since we use grub2 and BLS in all currentlysupported architectures. In fact, not setting it to `none`, will use the default `auto`, which will result in the run of `grub2-mkconfig`, which is not what we want and might even fail for us.

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2021-09-09 10:20 UTC, gicmo commented
For the record, the error Pierre saw when trying to do an upgrade commit without `bootloader: none`:

```
# ostree admin deploy cs8/x86_64/osbuild
note: Deploying commit 4db806215547c9893fde7a7795408a06e1c7ba6759740c31eb78b74a299d5ae2 which contains content in /var/lib that will be ignored.
Copying /etc changes: 2 modified, 0 removed, 12 added
error: Bootloader write config: grub2-mkconfig: Child process exited with code 1
```

2021-09-09 10:28 UTC, ondrejbudai requested changes
This needs an exception, blocking for now.

2021-09-09 11:23 UTC, cgwalters submitted a review, later dismissed

2021-09-09 12:11 UTC, martinezjavier submitted a review, later dismissed

2021-09-22 09:29 UTC, thozza commented
@gicmo can you please rebase this PR the get the F33 CI fixes?

2021-09-22 10:20 UTC, gicmo commented
Rebased, dropped the osbuild pinning.

2021-09-22 10:50 UTC, teg approved these changes

2021-09-22 10:50 UTC, ondrejbudai approved these changes

2021-09-22 13:39 UTC, ondrejbudai commented
We need osbuild 37 for the new ostree option, so I bumped the required osbuild version in the spec file and pinned it.

2021-09-23 15:14 UTC, thozza commented
The Base Tests on RHEL-8.3 are failing on `osbuild`. Reported https://github.com/osbuild/osbuild/issues/822

2021-09-24 08:25 UTC, thozza commented
We'll need to pin `osbuild` version https://github.com/osbuild/osbuild/commit/879c56a3b5896164444b0631743e5c9c7a6857d3 to resolve the osbuild issue in CI, once it's CI testing passes...

2021-09-24 12:04 UTC, ondrejbudai commented
I force-pushed a new osbuild pin, this should make the CI green. Thanks for pointing that out, @thozza!

2021-09-24 15:19 UTC, ondrejbudai commented
Rebased to fix a conflict caused by a recently merged PR.

2021-09-27 14:01 UTC, teg approved these changes

2021-09-27 18:09 UTC, ondrejbudai commented
Everything passed but Fedora 33 base tests. This is surely irrelevant so I decided to force-merge.

2021-09-27 18:10 UTC, merged