[WIP] Cloud cleaner aws
osbuild/osbuild-composer pull request #1968
Opened 2021-11-02 13:12 UTC by jabia99

Scheduled cloud cleaner only takes care of azure resources. This PR is intended to extend this functionality to AWS.

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2021-11-09 15:51 UTC, jrusz requested changes
So first I think you should rebase and drop the first two commits. I added several comments and also I believe that not all the AWS resources created in the `api.sh` are tagged and the naming convention is changed? Eg. on line 455 I still see uuidgen used...

2021-11-09 15:51 UTC, jrusz commented on schutzbot/scheduled_cloud_cleaner.sh
> +    RESOURCE_TYPE=$(echo "$RESOURCE_LIST" | jq .["$i"].type | tr -d '"')
This was done already in a different commit, just rebase.

2021-11-09 15:51 UTC, jrusz commented on test/cases/aws.sh
> +ARCH=$(uname -m)
This variable is defined by sourcing the script on line 4

2021-11-09 15:51 UTC, jrusz commented on test/cases/aws.sh
> +    	        }
I see wrong indentation here.

2021-11-09 15:51 UTC, jrusz commented on test/cases/aws.sh
> +echo "${AMI_IMAGE_ID}"
What is the purpose of these echos?

2021-11-09 15:51 UTC, jrusz commented on schutzbot/scheduled_cloud_cleaner.sh
> +#SSH_KEY=${SSH_DATA_DIR}/id_rsa
A forgotten commented out line?

2021-11-09 15:51 UTC, jrusz commented on schutzbot/scheduled_cloud_cleaner.sh
> +#----------------------------------
I suppose we do, this gives the container the necessary env vars and also mounts required directories inside it.

2021-11-09 15:51 UTC, jrusz commented on schutzbot/scheduled_cloud_cleaner.sh
> +			#$AWS_CMD ec2 terminate-instances --instance-id "${INSTANCE_ID}"
Since the cloud-cleaner should only be ran in a scheduled pipeline which won't run this code until it gets merged it's fine to have it uncommeted.

2021-11-09 15:51 UTC, jrusz commented on schutzbot/scheduled_cloud_cleaner.sh
> +        if [[ ${TAG} =~ "gitlab-ci-test" && ${TAG_VALUE} =~ "true" ]]; then
In the test statement you're not comparing it to a regex so you should be able to just use `==`

2021-11-09 15:51 UTC, jrusz commented on schutzbot/scheduled_cloud_cleaner.sh
> +	TAG_VALUE=$(echo ${image} | jq .Tag.Value)
Fix indent please.

2021-11-09 15:51 UTC, jrusz commented on schutzbot/scheduled_cloud_cleaner.sh
> +			#$AWS_CMD ec2 deregister-image --image-id "${IMAGE_ID}"
Same as comments above

2021-11-09 15:51 UTC, jrusz commented on schutzbot/scheduled_cloud_cleaner.sh
> +			#$AWS_CMD ec2 delete-snapshot --snapshot-id "${SNAPSHOT_ID}"
Same as above.

2021-11-09 15:58 UTC, jabia99 commented
> So first I think you should rebase and drop the first two commits. I added several comments and also I believe that not all the AWS resources created in the `api.sh` are tagged and the naming convention is changed? Eg. on line 455 I still see uuidgen used...

Yes, sorry I forgot to mention this, I still have to update `api.sh` to tag the resources and use `TEST_ID` instead of the uuid

2021-11-11 09:31 UTC, jrusz requested changes
Looks good, I like it, getting one step closer to cleaning all clouds regularly :) ... Just one thing, please remove the merge commit and do a rebase on main instead, we don't make merge commits :)

2021-11-11 11:12 UTC, jrusz approved these changes
LGTM

2021-11-11 11:53 UTC, jrusz approved these changes

2021-11-11 14:42 UTC, merged