osbuild: check if result objects are nil in Write()
osbuild/osbuild-composer pull request #2029
Opened 2021-11-17 16:14 UTC by achilleas-k

Cherry picked fix from #2022.

osbuild2 result does not have a `Write()` method in 8.5 so only osbuild1 needs the fix.

2021-11-18 16:11 UTC, ondrejbudai requested changes
oh... this is against 8.5... What's the plan here? Do we want to backport to z-stream? What doesn't actually work?

Blocking for now, if we want to backport, we need a bug firstly with the right acks.

2021-11-18 16:50 UTC, Gundersanne commented
The bug was reported on slack; https://github.com/osbuild/osbuild-composer/issues/2002

2021-11-19 17:27 UTC, achilleas-k commented
The idea was to backport, yes.  I opened the PR while we were chatting with Sanne and was going to write the bz for it but got held up by other things.

I think it's worth backporting.  This isn't very difficult to trigger and even if it's just for on-prem, it's still annoying.

2021-11-23 10:50 UTC, Gundersanne commented
This needs changes to the tests I think :/  I'm guessing 8.5 nightlies don't exist anymore

2022-03-02 13:10 UTC, achilleas-k commented
Closing.  Stale and irrelevant.

2022-03-02 13:10 UTC, closed without merging