test: make test more resilient
osbuild/osbuild-composer pull request #2132
Opened 2021-12-16 11:12 UTC by jabia99

During manual cleanup of unused resources, the storage account can get
removed. The current storage account is not possible to remove
mannually, but adding this check to make it more resielient in future
scenarios.

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2021-12-16 13:44 UTC, jrusz requested changes
The idea behind the task was to create the storage account if it's removed not fail the test. so instead of the exit just use azure cli to create the storage account/storage container please. 

To test it you can temporarily change the variable to something else and see if it creates it and the test passes.

2021-12-17 10:35 UTC, jabia99 commented
> The idea behind the task was to create the storage account if it's removed not fail the test. so instead of the exit just use azure cli to create the storage account/storage container please.

I misunderstood the ticket. I added this functionality and I think it's working. (I tested the feature using the same code locally)

2021-12-17 14:26 UTC, ondrejbudai reviewed
I will let @jrusz decide on this but FWIW I like this. :)

2021-12-17 15:05 UTC, jrusz approved these changes
Sorry I forgot about this, got dragged into other stuff. It looks good and if you say it works, let's merge it :)

2021-12-17 15:05 UTC, merged