Tracing: deactivate iostat by default
osbuild/osbuild-composer pull request #2179
Opened 2022-01-12 09:03 UTC by lavocatt

When iostat runs it can prevent the script from exiting from a failure.
Until we have a better solution for this, prevent iostat to start.

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2022-01-12 12:39 UTC, lavocatt commented
I integrated this commit also in this pr https://github.com/osbuild/osbuild-composer/pull/2176 and some jobs hanged. So iostat might not be the faulty part.

2022-01-12 16:35 UTC, achilleas-k commented
> I integrated this commit also in this pr #2176 and some jobs hanged. So iostat might not be the faulty part.

Interesting.  I wonder what else might have changed to be causing the issue.

2022-01-12 16:55 UTC, lavocatt commented
On slack @jrusz mentioned that "only the Installer job was stuck and that's because of the journal watcher not being killed properly on exit. It's missing this https://github.com/osbuild/osbuild-composer/commit/bc1a7dc30c4f1729d23bf028f44e35f74ed7d7e6"

I'm gonna try that, thanks @jrusz

2022-01-17 14:16 UTC, jrusz commented
@lavocatt Why did you decide to close this PR?

2022-01-17 16:01 UTC, lavocatt commented
Oh yes, because I wanted to apply the patch in an other one. Sorry, I should name why I'm closing stuff..

2022-01-17 16:39 UTC, jrusz commented
Oh ok, I wanted to ask about this, because IMO it's currently making the CI unusable, lots of jobs waiting for the 4 hour timeout so it would be nice if we can solve this sooner rather than later.

2022-01-18 08:13 UTC, lavocatt commented
Yes you are right, In the end I'll keep this PR opened to not forget the subject

2022-01-18 08:33 UTC, jrusz requested changes
Since we're deactivating it, could you please remove it everywhere? I can see more instances of the `start_iostats.sh` and `stop_iostats.sh` eg line 48,50 ... And also please remove `iostats.json` from the artifacts too :)

2022-01-18 09:22 UTC, jrusz commented
To clarify I have no problem with keeping it and running it, the problem is with how it's being ran now. If the main script fails, the iostat script running in background is preventing the CI from failing and it waits for timeout which results in dozens of jobs being stuck waiting for timeout and IMO making the CI unusable.

Since I saw you remove it from some of the jobs I thought why not remove it from all the jobs? I'm talking about the `.gitlab-ci.yml` file, the scripts themselves can be left alone.

The other option that I would go for is to run this iostat script from within the main script of each job, for example by sourcing it and then having a `trap` to kill it on exit. Similar to how we do it with the journal watcher. This could maybe be added to `tools/set-env-vars.sh` I think because it's sourced in every script AFAIK. I can try creating a PoC of what I mean, I'm not 100% sure it would work as I think it would but at least I could figure something out.

2022-01-18 09:45 UTC, jrusz commented
Made one more test, now I'm 100% sure iostats are freezing CI https://github.com/osbuild/osbuild-composer/pull/2198 so we need to do something about it.

2022-01-18 10:29 UTC, lavocatt commented
> Since I saw you remove it from some of the jobs I thought why not remove it from all the jobs? I'm talking about the .gitlab-ci.yml file, the scripts themselves can be left alone.

That makes sense. cleaning the gitlab yml file and keeping the file is nice.

I'd be also happy with the other solution, it looks neat.

2022-01-31 11:44 UTC, closed without merging