FS minimum size
osbuild/osbuild-composer pull request #2353
Opened 2022-02-23 15:42 UTC by kingsleyzissou

This pull request includes:
- enable `/tmp` mountpoint for rhel86 & rhel90
- ensure minimum size of 1GB for all file systems, except `/usr` which is set to 2GB (fixes #2347)

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2022-02-23 16:03 UTC, teg requested changes
Minor request to change a function name.

2022-02-23 19:00 UTC, teg approved these changes

2022-02-24 09:59 UTC, gicmo approved these changes
Thanks so much!

2022-02-24 10:00 UTC, gicmo commented
All green expect the koji integration test on CS9, which is expected to fail. Will merge.
<img width="1603" alt="Screenshot 2022-02-24 at 10 55 53" src="https://user-images.githubusercontent.com/2040/155502141-9824499a-8f50-418c-945e-17fe0179a5a3.png">

2022-02-24 10:00 UTC, merged