internal/distro/rhel{86,90}: drop console kargs from raw image deploy…
osbuild/osbuild-composer pull request #2377
Opened 2022-03-01 08:59 UTC by runcom

…ment

Using the simplified installer we were experiencing slow system boots.
Turns out we're incurring into https://bugzilla.redhat.com/show_bug.cgi?id=1839923
This patch just drops the console kargs - to be aligned with the
anaconda installer that doesn't experience this slow down.
The slow down doesn't happen on virtual machines as there's always a
ttyS0 there

Signed-off-by: Antonio Murdaca <runcom@linux.com>

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2022-03-01 09:08 UTC, runcom commented
oh right, this needs manifests regeneration :)

2022-03-01 12:57 UTC, achilleas-k approved these changes
LGTM :)
Thanks!

2022-03-02 12:50 UTC, ondrejbudai requested changes
Needs an exception I think.

2022-03-14 16:31 UTC, ondrejbudai approved these changes

2022-03-14 16:31 UTC, merged

2022-03-14 16:32 UTC, ondrejbudai commented
FTR:
- https://bugzilla.redhat.com/show_bug.cgi?id=2059429
- https://bugzilla.redhat.com/show_bug.cgi?id=2062132