rpmplint: trust osbuild-composer repository
osbuild/osbuild-composer pull request #2627
Opened 2022-05-09 15:27 UTC by jrusz

Git v2.35.2 brought some security fixes which prevents interaction with
repository if it's not owned by the user who cloned it. More info here:
https://github.blog/2022-04-12-git-security-vulnerability-announced/

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2022-05-09 16:04 UTC, ondrejbudai commented
Chm but why is the owner different?

2022-05-10 06:53 UTC, jrusz commented
> Chm but why is the owner different?

I have no idea, could it be that the checkout action runs under different user?

2022-05-10 10:23 UTC, thozza submitted a review, later dismissed
Thank you for fixing this!

2022-05-10 10:47 UTC, ondrejbudai requested changes

2022-05-10 11:24 UTC, ondrejbudai approved these changes

2022-05-10 11:25 UTC, merged