COMPOSER-1576: Start building rpms on 9.0 and 8.6 GA
osbuild/osbuild-composer pull request #2716
Opened 2022-06-02 09:08 UTC by atodorov

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2022-06-02 09:17 UTC, jrusz approved these changes
LGTM if the rpmbuild jobs pass.

2022-06-02 09:22 UTC, ondrejbudai requested changes

2022-06-02 09:22 UTC, ondrejbudai commented on .gitlab-ci.yml
>            - aws/rhel-8.5-ga-x86_64
These need to be removed, otherwise we will run into conflicts. They use the same URL as rhel-8.6-ga so it's fine to remove them.

2022-06-02 09:42 UTC, ondrejbudai submitted a review, later dismissed

2022-06-02 11:25 UTC, jrusz commented
@atodorov Since it's a draft PR, Gitlab CI jobs wait for manual trigger, just fyi...

2022-06-02 12:33 UTC, jrusz commented
Ugh, it's failing because it's adding the nightly repos from Schutzfile to GA images. We didn't have this last time and it seems we didn't really take into account the possibility of having both nightly and ga of the same version...

@atodorov try adding `-nightly` to `rhel-8.6` and `rhel-9.0` in the Schutzfile. It should work only for nightlies then based on this https://github.com/osbuild/gitlab-ci-terraform-executor/blob/main/prepare#L77 but it will probably break something else, like the dependency in deploy.sh https://github.com/osbuild/osbuild-composer/blob/main/schutzbot/deploy.sh#L101

2022-06-02 12:48 UTC, ondrejbudai commented
Or just remove 8.6 nightly testing.

2022-06-02 13:00 UTC, jrusz commented
> Or just remove 8.6 nightly testing.

That should work too I guess, but remove 9.0 nightly as well right?

2022-06-03 07:09 UTC, jrusz commented on .gitlab-ci.yml
>          INTERNAL_NETWORK: ["true"]
CI says "yaml invalid" I think he means this, maybe comment out the whole job for now if it's not going to have any runners?

2022-06-06 10:53 UTC, ondrejbudai approved these changes

2022-06-06 10:53 UTC, merged

2022-06-07 11:20 UTC, thozza commented on .gitlab-ci.yml
> +#        INTERNAL_NETWORK: ["true"]
@atodorov you shouldn't have disabled this test, but rather switch it to use the RHEL-9.0 GA runner.

The job does not care about the runner, we just used the latest RHEL version that was available at the time.

Please fix it and re-enable it.