templates: update dashboards to include tenant
osbuild/osbuild-composer pull request #2756
Opened 2022-06-15 20:05 UTC by chloenayon

Add a tenant variable to the composer dashboard.

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2022-06-23 15:49 UTC, Gundersanne commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +    "uid": "JLSCLdqnk",
Keep the `image-builder-worker` uid here; it determines the url of the dashboard.

2022-06-23 15:49 UTC, Gundersanne commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +    "version": 3,
Let's make it version 7?

2022-06-23 15:49 UTC, Gundersanne commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +  }
Newline at the end please ^_^

2022-06-23 16:48 UTC, kingsleyzissou commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +    "annotations": {
I think we need two more spaces of indentation here

2022-06-28 08:21 UTC, Gundersanne requested changes
Good direction. A few things

- don't pin of the datasource ( I made that mistake a few times :|)
- the job wait duration on the db you linked is collapsed by default, it can be expanded
- selecting multiple tenants doesn't work, instead of a multi select we could just have a "*" option (and "*" can be the default)


A lot of this is stuff that gets changed randomly during exporting (like the datasource thing). `git add -p` is handy here. And it's worthwhile to reimport the json after having exported/committed it to see the diff between them.

2022-06-28 08:21 UTC, Gundersanne commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +
nitpick, empty whitespace

2022-06-28 08:21 UTC, Gundersanne commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +        "from": "now-30d",
Keep the now-28d as default; all our SLOs are calculated across 28d and this way the rest of the graphs (which are time-dependent) show the same time period by default; it's a small thing but still.

2022-06-28 08:21 UTC, Gundersanne commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +              "value": "7d"
keep this at 6h by default, this determines the granularity/the amount of the data points shown; 6h is a happy medium between smoothing out and showing spikes.

2022-06-28 08:21 UTC, Gundersanne commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +              "value": "app-sre-stage-01-prometheus"
Default should be app-sre-prod-04-prometheus here so also revert this.

2022-06-28 08:21 UTC, Gundersanne commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +              },
don't pin the datasource; it should be "uid": "${datasource}" always.

2022-06-28 08:21 UTC, Gundersanne commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +                "uid": "gH4yqWBnz"
Same

2022-06-28 08:21 UTC, Gundersanne commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +                "uid": "gH4yqWBnz"
Same

2022-06-28 08:21 UTC, Gundersanne commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +                "uid": "gH4yqWBnz"
idem

2022-06-28 08:21 UTC, Gundersanne commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +                "uid": "gH4yqWBnz"
"${datasource}"

2022-06-28 08:21 UTC, Gundersanne commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +                "uid": "gH4yqWBnz"
etc.

2022-07-08 16:02 UTC, kingsleyzissou requested changes

2022-07-08 16:02 UTC, kingsleyzissou commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +                "uid": ""${datasource}""
Same here. I think there are a few like this

2022-07-08 16:02 UTC, kingsleyzissou commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +              "expr": "(sum(rate(image_builder_worker_total_jobs{type=~\"osbuild:.*\", status!=\"4xx\", tenant=\"$tenant\"}[$interval])) OR on() vector(0))\n- \n(sum(rate(image_builder_worker_total_j
If you change this `tenant=\"$tenant\"` to `tenant=~\"$tenant\"` for all instances, the selection should work.

2022-07-08 16:02 UTC, kingsleyzissou commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +                "selected": false,
We should leave `6h` as the default resolution

2022-07-08 16:04 UTC, kingsleyzissou commented
Sorry been meaning to get back to this, I had a look this morning and changing from `tenant=\"$tentant\"` to `tenant=~\"$tentant\"` should do the trick.

2022-07-11 15:55 UTC, kingsleyzissou approved these changes
Thanks!

2022-07-14 16:02 UTC, kingsleyzissou requested changes

2022-07-14 16:02 UTC, kingsleyzissou commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +            "current": {
hey @chloenayon sorry for the change request on this :/
See this conversation here:
https://github.com/RedHatInsights/image-builder-frontend/pull/753#discussion_r921235240

Could you please update this to have an "All" option and making it the default. I think you can add it through the GUI:
![image](https://user-images.githubusercontent.com/20438192/179025969-f3414c11-dfbc-49fa-87a2-b7ca31088092.png)

2022-07-14 16:02 UTC, kingsleyzissou commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +            "current": {
Setting the custom all value to `.*` will give us a regex wildcard

2022-07-15 15:04 UTC, kingsleyzissou submitted a review, later dismissed
Awesome, thanks so much!

2022-07-18 11:03 UTC, Gundersanne requested changes
1 last nitpick

2022-07-18 11:03 UTC, Gundersanne commented on templates/dashboards/grafana-dashboard-image-builder-worker-general.configmap.yml
> +      "version": 2,
```
 "uid": "image-builder-worker",
      "version": 7,
```

-> bump version by 1, keep uid the same

2022-07-18 16:54 UTC, Gundersanne approved these changes
lgtm, thank you!

2022-07-18 16:54 UTC, Gundersanne commented
dashboards updated, codebase/tests not affect. admin merging

2022-07-18 16:55 UTC, merged