Filesystems test update
osbuild/osbuild-composer pull request #2843
Opened 2022-07-19 15:41 UTC by jrusz

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2022-07-20 08:39 UTC, jrusz commented
@atodorov Can you please review the first commit? I'm going to remove the commented code and drop the other two commits if you think it's fine.
Passing pipeline: https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/pipelines/591619561
Deliberately failed pipeline: https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/pipelines/592120193
I've also checked the second scenario locally and is imo working reliably like this

2022-07-20 09:14 UTC, atodorov requested changes
Minor changes requested.

2022-07-20 09:14 UTC, atodorov commented on test/cases/filesystem.sh
> +
I would prefer this to be a function to avoid repetition. Otherwise looks good.

2022-07-20 11:05 UTC, atodorov submitted a review, later dismissed

2022-07-20 14:47 UTC, jrusz commented
@atodorov I cherry-picked your commit disabling the `cloud-image-val` because it's now failing on Fedora-35 as well and effectively blocking the CI.

2022-07-20 15:35 UTC, atodorov commented
> `cloud-image-val` because it's now failing on Fedora-35

oh boy

2022-07-21 08:04 UTC, atodorov approved these changes

2022-07-21 11:17 UTC, merged