distro/rhel90: edge images default to LVM
osbuild/osbuild-composer pull request #2861
Opened 2022-07-27 13:11 UTC by 7flying

Change partition tables on `edgeBase` images to use 'LVM partitioning'.
We need to ensure that LVM stages are done before LUKS stages (e.g. remove-key) or the pipelines will break (we cannot open a device when its password has changed).

This PR requires changes on `coreos-installer-dracut/dracut/scripts/coreos-installer-growfs`(PR incoming) required by rhel90-edge images to account for the change from traditional partitioning to LVM, otherwise the image will boot on an emergency shell and will need a manual reboot. This is why this marked as a draft PR.

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2022-07-27 13:49 UTC, gicmo commented
LGTM on a first glance!

2022-07-28 03:24 UTC, henrywang commented
@7flying Thanks for doing this! :+1: 
Is this change only on RHEL 9.1? No LVM on RHEL 8.7? Thanks.

2022-07-28 07:18 UTC, 7flying commented
@henrywang I will send changes 8.7 on a different PR!

2022-08-11 13:19 UTC, 7flying commented
Since @gicmo's last comment I've added a test and modified the partition table to set 9GB to the rootlv on the edge images. I've also linked the relevant PR to coreos-installer-dracut.

2022-08-22 10:16 UTC, henrywang commented
@7flying This PR needs a new `coreos-installer` release which include MR https://gitlab.com/redhat/centos-stream/rpms/rust-coreos-installer/-/merge_requests/16? Thanks.

2022-08-24 08:13 UTC, runcom commented
@achilleas-k can you review this and https://github.com/osbuild/osbuild-composer/pull/2904 - these are required for us to ship lvm images

2022-08-24 09:49 UTC, achilleas-k requested changes
Looks good, but we're going to need manifest updates.  You can run 
```
./tools/test-case-generators/generate-all-test-cases \
    --output test/data/manifests \
    --image-type edge-raw-image \
    manifests
```
to generate new ones.

2022-08-24 10:17 UTC, runcom commented
@achilleas-k I'm not sure the test failure is related here (but have no familiarity with the failure :))

2022-08-24 11:25 UTC, runcom commented
This looks good now @achilleas-k (only f35aarch64 is still building) ptal

2022-08-25 12:44 UTC, achilleas-k approved these changes
All good now.  Thank you.

2022-08-26 10:18 UTC, runcom commented
> @runcom LVM testing updated.

they're still failing now

2022-08-27 10:15 UTC, henrywang commented
@runcom All green except simplified installer.

2022-08-27 13:53 UTC, runcom commented
> @runcom All green except simplified installer.

we just a new working snapshot

2022-09-15 19:43 UTC, runcom commented
I'll remove cs9 tests tomorrow to make this happy

2022-09-19 09:22 UTC, ondrejbudai approved these changes

2022-09-20 10:22 UTC, henrywang commented
@runcom @achilleas-k The only failure is `aws.sh` test on aarch64 which is not caused by this PR. Can we land this PR? Thanks.

2022-09-21 15:14 UTC, ondrejbudai submitted a review, later dismissed

2022-09-21 15:16 UTC, ondrejbudai commented
@runcom Can you rebase, please? I have no idea what's wrong, GitHub doesn't allow me to merge without rebasing. :shrug:

2022-09-21 17:18 UTC, henrywang commented
> @runcom Can you rebase, please? I have no idea what's wrong, GitHub doesn't allow me to merge without rebasing. shrug

Thanks @ondrejbudai. Rebased.

2022-09-22 08:20 UTC, ondrejbudai approved these changes
Let's get this in!

2022-09-22 08:20 UTC, merged