DEBUG: try only medium runners
osbuild/osbuild-composer pull request #2866
Opened 2022-07-29 07:11 UTC by jrusz

Medium runners might be enough and will give us more jobs in parallel

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2022-08-02 08:47 UTC, atodorov requested changes
Minor change requested.

2022-08-02 08:47 UTC, atodorov commented on .gitlab-ci.yml
> +          # - rhos-01/fedora-36-x86_64
ATM there are fedora-36-x86_64 and fedora-36-x86_64-large runner definitions so you can uncomment this line.

2022-08-02 13:01 UTC, atodorov submitted a review, later dismissed

2022-08-02 14:16 UTC, jrusz commented
Hm, this will probably require some reshuffling in the `ostree-rebase.sh` or somehow forcing `virt-install` to use less memory, he doesn't listen to my `--ram 1536` we can't spawn 2 VMs with 3 GB memory on a 4 GB machine.

2022-08-03 08:00 UTC, jrusz commented
I've decided to split the `ostree-rebase.sh` test into bios and uefi scenario. This won't add load on the CI as 2 medium runners = 1 large runner and after this change we're still getting 26 more Openstack runners to use (was supposed to be 30) which is still good IMO.

2022-08-08 09:31 UTC, ondrejbudai approved these changes
Thanks!

2022-08-08 09:32 UTC, merged