Modify repositories/rhel-xy.json file before testing nightly compose
osbuild/osbuild-composer pull request #2894
Opened 2022-08-15 10:20 UTC by atodorov

- uses a wildcard match for sed in order to replace only lines which
  match and keep the rest intact
- the schutzbot/prepare-rhel-internal-json.sh script will be executed
  before mockbuild.sh

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2022-08-15 12:17 UTC, ondrejbudai commented on tools/provision.sh
> +sudo composer-cli status show
This should be moved under the `AUTH_METHOD_NONE` section, tests meant for the service don't have Weldr enabled at all.

2022-08-16 12:51 UTC, atodorov commented
Nightly test job is here:
https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/pipelines/613845213

failures are unrelated.

2022-08-16 13:04 UTC, jrusz requested changes
> * the schutzbot/prepare-rhel-internal-json.sh script will be executed
>   before mockbuild.sh

How and why? Looking at the `.gitlab-ci.yml` file I can see it's running the `mockbuild.sh` first to create the test rpms and the it's running the `prepare-rhel-internal` stage...

Also this means that currently the `prepare-rhel-internal` is just making sure the correct system repos are set and optinally a custom `-tests` package repo url is used, right?

Otherwise it looks good I like the simple `sed` to replace the source repos during provisining of the SUT.

2022-08-16 14:02 UTC, jrusz commented
@atodorov the issue is that this https://github.com/osbuild/osbuild-composer/blob/main/test/cases/regression-composer-works-behind-satellite.sh#L127 doesn't return anything

Latest run on main: https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/2887431645#L3037
Run with this PR:  https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/2890016059#L3183

And the reason seems to be this one:https://github.com/osbuild/osbuild-composer/blob/main/test/cases/regression-composer-works-behind-satellite.sh#L101 
It's expecting the repo name to be all lowercase in nightly run

2022-08-17 10:21 UTC, atodorov commented
> > * the schutzbot/prepare-rhel-internal-json.sh script will be executed
> >   before mockbuild.sh
> 
> How and why? Looking at the `.gitlab-ci.yml` file I can see it's running the `mockbuild.sh` first to create the test rpms and the it's running the `prepare-rhel-internal` stage...
> 

^^^ no longerr valid, that was an initial approach. Commit log message updated to match.


> Also this means that currently the `prepare-rhel-internal` is just making sure the correct system repos are set and optinally a custom `-tests` package repo url is used, right?
> 

Yes.

> Otherwise it looks good I like the simple `sed` to replace the source repos during provisining of the SUT.

2022-08-17 10:27 UTC, atodorov commented
> And the reason seems to be this one:https://github.com/osbuild/osbuild-composer/blob/main/test/cases/regression-composer-works-behind-satellite.sh#L101

Good catch, thanks. I didn't scroll all the way down apparently.  Fixed in the latest commit.

2022-08-17 10:51 UTC, atodorov commented
9.1 test job:
https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/pipelines/615634410

8.7 test job:
https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/pipelines/615634450

2022-08-17 12:46 UTC, jrusz approved these changes
Alright, nightly pipelines looks good, so LGTM

2022-08-18 11:00 UTC, merged