distro/rhel8: edge 87 images default to LVM
osbuild/osbuild-composer pull request #2904
Opened 2022-08-18 14:48 UTC by 7flying

Change partition tables on edgeBase images to use 'LVM partitioning'. This is similar to [osbuild-composer PR#2861](https://github.com/osbuild/osbuild-composer/pull/2861) but for 8.7.

This PR needs changes on RHEL 8.7 LVM dracut module, concretely this [commit](https://github.com/dracutdevs/dracut/commit/f6f393f550625e3e1c968ef32d6d7bdd90f51d73) needs to be backported.

Marked as ready but don't merge yet.

This pull request includes:

- [x] adequate testing for the new functionality or fixed issue (testing on this previous PR: [osbuild-composer PR#2861](https://github.com/osbuild/osbuild-composer/pull/2861))
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2022-08-22 10:12 UTC, henrywang commented
@7flying This PR still needs `coreos-installer` release in RHEL 8.7, right? Thanks.

2022-08-24 08:13 UTC, runcom commented
> This PR needs changes on RHEL 8.7 LVM dracut module, concretely this [commit](https://github.com/dracutdevs/dracut/commit/f6f393f550625e3e1c968ef32d6d7bdd90f51d73) needs to be backported.

@nullr0ute is there a bug for this already?

2022-08-24 09:50 UTC, achilleas-k requested changes
Looks good, but we're going to need manifest updates.  You can run 
```
./tools/test-case-generators/generate-all-test-cases \
    --output test/data/manifests \
    --image-type edge-raw-image \
    manifests
```
to generate new ones.

2022-10-19 06:32 UTC, henrywang commented
LVM will not be supported on RHEL 8. So close this PR. Let's re-open it when we have requirement for this feature on RHEL 8.

2022-10-19 06:32 UTC, closed without merging