schutzbot: Fast-forward main-success branch after green main run
osbuild/osbuild-composer pull request #2922
Opened 2022-08-26 11:03 UTC by Gundersanne

The main-success branch can be tracked by stage deployments to make sure
CI is green before deploying to stage.

2022-08-26 11:14 UTC, teg commented
Nitpick of the century, but could we name the branch something like `release`? `main-success` confused me for a bit.

2022-08-26 11:22 UTC, Gundersanne commented
> Nitpick of the century, but could we name the branch something like `release`? `main-success` confused me for a bit.

Open to suggestions!

2022-08-27 14:51 UTC, teg commented
> > Nitpick of the century, but could we name the branch something like `release`? `main-success` confused me for a bit.
> 
> Open to suggestions!

I suggest `release` ;)

2022-08-29 11:53 UTC, ondrejbudai approved these changes

2022-08-29 14:36 UTC, teg approved these changes

2022-08-30 13:16 UTC, ondrejbudai requested changes

2022-08-30 13:23 UTC, Gundersanne commented
This needs to actually check if the pipeline succeeded ._.

2022-08-30 13:25 UTC, Gundersanne commented on schutzbot/update_github_status.sh
> +if [ "$CI_COMMIT_BRANCH" = "main" ]; then
Lol I saw the same thing when rebasing just now ._.

2022-08-31 11:14 UTC, ondrejbudai approved these changes

2022-09-02 09:05 UTC, merged