ignition: enable systemd firstboot condition through kargs
osbuild/osbuild-composer pull request #3308
Opened 2023-02-27 09:02 UTC by runcom

This is a workaround to make the systemd believe it's firstboot when ignition runs on real firstboot.
Right now, since we ship /etc/machine-id, systemd thinks it's not firstboot and ignition depends on it to run on the real firstboot to enable services from presets. Since this only applies to artifacts with ignition and changing machineid-compat at commit creation time may have undesiderable effect, we're doing it here as a stopgap. We may revisit this in the future.

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2023-02-27 09:11 UTC, thozza reviewed
This looks good. I expect that you will also need to regenerate image test manifests that use the commit-deployment pipeline.

2023-02-27 09:11 UTC, thozza commented on internal/osbuild/ignition_stage.go
> +	Network []string `json:"network"`
This should be marked as `omitempty`, since this is not a required property.

2023-02-27 09:47 UTC, thozza approved these changes
LGTM 👍

2023-02-27 13:34 UTC, atodorov requested changes

2023-02-27 13:34 UTC, atodorov commented on test/data/ansible/check_ostree.yaml
> +            success_msg: "hello.service started and working"
I don't understand how is this assertion related to `systemd.condition-first-boot=true` argument ? Can you clarify ?

2023-02-28 09:35 UTC, thozza commented
Hi @runcom.

Please:

1. Squash the two commits into a single one or alternatively do the SPEC file and Schutzfile update in a single (optionally separate) commit.
2. Add a note about the reason to depend on osbuild v81 in the commit message that changes the dependency (basically note that it is because of the fixed Ignition stage).

Otherwise this looks good. Thanks 👍

2023-02-28 11:27 UTC, runcom commented
> * Squash the two commits into a single one or alternatively do the SPEC file and Schutzfile update in a single (optionally separate) commit.
> * Add a note about the reason to depend on osbuild v81 in the commit message that changes the dependency (basically note that it is because of the fixed Ignition stage).

squashed and added note, thanks @thozza

2023-02-28 12:35 UTC, thozza approved these changes

2023-02-28 13:06 UTC, achilleas-k approved these changes

2023-02-28 14:40 UTC, atodorov commented on test/data/ansible/check_ostree.yaml
> +            success_msg: "hello.service started and working"
FTR see https://redhat-internal.slack.com/archives/C0235DZB0DT/p1677592474917199

2023-02-28 17:35 UTC, thozza commented
All CI jobs passed, except for the VSphere ones, which are affected by a known DNS issue. Admin-merging, because this is an important bugfix.

2023-02-28 17:35 UTC, merged