Include test for edge-ami image type
osbuild/osbuild-composer pull request #3542
Opened 2023-07-03 16:24 UTC by mcattamoredhat

This pull request includes:

Now that osbuild-composer is able to generate an edge AMI that can be uploaded and deployed on AWS, it would be useful to include a dedicated test script for automation.

ostree-ami-image.sh uses osbuild-composer to build edge-ami image type, then upload it to a S3 bucket and deploy an EC2 instance using that image.

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2023-07-04 03:15 UTC, henrywang requested changes

2023-07-04 03:15 UTC, henrywang commented on test/cases/ostree-ami-image.sh
> +# With new ostree-libs-2022.6-3, edge vm needs to reboot twice to make the /sysroot readonly
I think the ami image doesn't need reboot again, you can double confirm with devel.

2023-07-04 03:15 UTC, henrywang commented on test/cases/ostree-ami-image.sh
> +##################################################################
The ami image imported should support both bios and uefi. So we don't need two test scenarios.

2023-07-04 03:15 UTC, henrywang commented on test/cases/ostree-ami-image.sh
> +greenprint "Share ssh public key with AWS"
All the following things, like keypair, vpc, internet gateway, subnet, you have two choices to configure them for test running in parallel support.

1. each test uses its own above things, their name should be random
2. each test uses the same above things, you need check them existing first. If they exist, just ignore configuration.

2023-07-04 03:15 UTC, henrywang commented on test/cases/ostree-ami-image.sh
> +# No RT kernel in Fedora
Save above.

2023-07-04 03:15 UTC, henrywang commented on test/cases/ostree-ami-image.sh
> +# Add directory and files customization, and services customization for testing
You already configure CUSTOM_DIRS_FILES to false, so this part of configuration is not use able.
Please confirm with devel for ami image custom dir support.

2023-07-04 03:15 UTC, henrywang commented on test/cases/ostree-ami-image.sh
> +ansible_user=admin
Where do you test ignition user? You should test ignition user here.

2023-07-04 03:15 UTC, henrywang commented on test/cases/ostree-ami-image.sh
> +greenprint "🧹 Clean up AWS EC2 resources"
you have clean_up function already, can you move all clean up things there?

2023-07-04 03:15 UTC, henrywang commented on test/cases/ostree-ami-image.sh
> +ansible_user=admin
test ignition user here.

2023-07-10 15:16 UTC, mcattamoredhat commented on test/cases/ostree-ami-image.sh
> +
Ok, done.

2023-07-20 09:15 UTC, henrywang approved these changes
LGTM. Thanks!

2023-07-20 09:18 UTC, merged