Start collecting logs from virt-install
osbuild/osbuild-composer pull request #3557
Opened 2023-07-17 08:08 UTC by atodorov

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2023-07-17 14:38 UTC, henrywang commented on test/cases/minimal-raw.sh
> +                   --noreboot \
Hi @atodorov. This extra-args does not work with `--import` and report `ERROR    Kernel arguments are only supported with location or kernel installs.` Error.

2023-07-18 06:56 UTC, jrusz requested changes
What about the https://github.com/osbuild/osbuild-composer/blob/main/tools/libvirt_test.sh ? This is the test that was causing us problems last time because there were no logs...

2023-07-18 12:54 UTC, jrusz reviewed
It looks good, but for some reason the log files from `libvirt.sh` test are empty, for example here https://s3.console.aws.amazon.com/s3/buckets/image-builder-ci-artifacts?region=us-east-1&prefix=osbuild-composer/PR-3557/4678004874/&showversions=false

The `aws_s3.sh` test which uses the same script does have the log content there though...

2023-07-18 13:15 UTC, jrusz commented
It's actually in all of the test scripts, I'm surprised it only caused issue in that one, can you update them as well please?

Also since I think we have the `get_compose_logs` function in all of the test scripts it would be better to change the libvrit log filename variable for consistency sake...

2023-07-19 08:04 UTC, jrusz approved these changes
LGTM

2023-07-21 10:10 UTC, ondrejbudai approved these changes
Thanks!

2023-07-21 10:10 UTC, ondrejbudai commented on tools/libvirt_test.sh
> +if [ ! -f "$VIRT_LOG" ]; then
nitpick: This isn't needed, `touch` just updates timestamps if the file already exists and returns 0.

2023-07-21 10:10 UTC, ondrejbudai commented
Just the packer job failed, that's completely unrelated.

2023-07-21 10:11 UTC, merged