Update test runners to Fedora 39
osbuild/osbuild-composer pull request #3820
Opened 2023-11-27 16:06 UTC by atodorov

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2023-11-27 16:08 UTC, achilleas-k approved these changes

2023-11-27 16:10 UTC, jrusz requested changes
Can you add an entry for Fedora-39 in `Schutzfile` as well please?

2023-12-07 17:23 UTC, achilleas-k submitted a review, later dismissed
LGTM!

2023-12-07 17:23 UTC, achilleas-k commented
Watching the filesystem test closely.

2023-12-07 17:34 UTC, achilleas-k commented
Same failure as before unfortunately.

2023-12-08 11:00 UTC, mvo5 commented
I puhsed a tiny commit to help debug this, the failure happens when f39 tries to mount the generated xfs partitions. The error code 32 from mount indicates a `mount failure` - context_mount.c generates some error output that appears to be swallowed by the way we call mount, I may push a small tweak to our code for this as well (if the current commit does not indicate the error already).

2023-12-08 12:59 UTC, mvo5 commented
I also opened https://github.com/osbuild/osbuild/pull/1490 in osbuild to make sure we get better error reporting from `MountGuard` in osbuild.

2023-12-08 14:32 UTC, atodorov commented
@mvo5 you can update this section in `Schutzfile`

```
  "fedora-39": {
    "dependencies": {
      "osbuild": {
        "commit": "433515cff898168b204833941a6d32399152128b"
      }
    },
```

and reference your new osbuild commit, [d0c917f7d1dddc82b99c12bb73d19cf2c6e81400](https://github.com/osbuild/osbuild/pull/1490/commits/d0c917f7d1dddc82b99c12bb73d19cf2c6e81400). That should give you the error output in the context of this PR.

2023-12-08 16:34 UTC, mvo5 commented
> @mvo5 you can update this section in `Schutzfile`
> 
> ```
>   "fedora-39": {
>     "dependencies": {
>       "osbuild": {
>         "commit": "433515cff898168b204833941a6d32399152128b"
>       }
>     },
> ```
> 
> and reference your new osbuild commit, [d0c917f7d1dddc82b99c12bb73d19cf2c6e81400](https://github.com/osbuild/osbuild/pull/1490/commits/d0c917f7d1dddc82b99c12bb73d19cf2c6e81400). That should give you the error output in the context of this PR.
> 
> **Update:** I see that you've opened your PR from a fork. Maybe try a branch in the osbuild repo instead!

Thank you! The PR is scheduled for merging so hopefully just updating to osbuild@latest will be possible in a little bit :)

2023-12-11 17:33 UTC, mvo5 commented
Now it fails with:
```
...
Dec 11 17:22:20 ip-10-31-18-230.us-east-1.aws.redhat.com osbuild-worker[22946]: time="2023-12-11T17:22:20Z" level=info msg="    /run/osbuild/tree/etc/vconsole.conf written." jobId=acb0d67b-6055-459a-b3d2-0e2acde648fc
Dec 11 17:22:20 ip-10-31-18-230.us-east-1.aws.redhat.com osbuild-worker[22946]: time="2023-12-11T17:22:20Z" level=info msg="    Traceback (most recent call last):" jobId=acb0d67b-6055-459a-b3d2-0e2acde648fc
Dec 11 17:22:20 ip-10-31-18-230.us-east-1.aws.redhat.com osbuild-worker[22946]: time="2023-12-11T17:22:20Z" level=info msg="      File \"/run/osbuild/bin/org.osbuild.keymap\", line 114, in <module>" jobId=acb0d67b-6055-459a-b3d2-0e2acde648fc
Dec 11 17:22:20 ip-10-31-18-230.us-east-1.aws.redhat.com osbuild-worker[22946]: time="2023-12-11T17:22:20Z" level=info msg="        r = main(args[\"tree\"], args[\"options\"])" jobId=acb0d67b-6055-459a-b3d2-0e2acde648fc
Dec 11 17:22:20 ip-10-31-18-230.us-east-1.aws.redhat.com osbuild-worker[22946]: time="2023-12-11T17:22:20Z" level=info msg="      File \"/run/osbuild/bin/org.osbuild.keymap\", line 107, in main" jobId=acb0d67b-6055-459a-b3d2-0e2acde648fc
Dec 11 17:22:20 ip-10-31-18-230.us-east-1.aws.redhat.com osbuild-worker[22946]: time="2023-12-11T17:22:20Z" level=info msg="        configure_xkb(tree, x11_keymap)" jobId=acb0d67b-6055-459a-b3d2-0e2acde648fc
Dec 11 17:22:20 ip-10-31-18-230.us-east-1.aws.redhat.com osbuild-worker[22946]: time="2023-12-11T17:22:20Z" level=info msg="      File \"/run/osbuild/bin/org.osbuild.keymap\", line 77, in configure_xkb" jobId=acb0d67b-6055-459a-b3d2-0e2acde648fc
Dec 11 17:22:20 ip-10-31-18-230.us-east-1.aws.redhat.com osbuild-worker[22946]: time="2023-12-11T17:22:20Z" level=info msg="        with open(f\"{tree}/etc/X11/xorg.conf.d/00-keyboard.conf\", \"w\", encoding=\"utf8\") as f:" jobId=acb0d67b-6055-459a-b3d2-0e2acde648fc
Dec 11 17:22:20 ip-10-31-18-230.us-east-1.aws.redhat.com osbuild-worker[22946]: time="2023-12-11T17:22:20Z" level=info msg="    FileNotFoundError: [Errno 2] No such file or directory: '/run/osbuild/tree/etc/X11/xorg.conf.d/00-keyboard.conf'" jobId=acb0d67b-6055-459a-b3d2-0e2acde648fc
```
which got fixed as part of https://github.com/osbuild/osbuild/pull/1441 in https://github.com/osbuild/osbuild/pull/1441/commits/6e3ca59657465b7b930c122e0efa7f984c27ff2c so  I suspect the worker is using a slightly older version of osbuild.

2023-12-12 17:44 UTC, mvo5 commented
And we finally have a more decent error message:
```
Traceback (most recent call last):
  File "/usr/libexec/osbuild-composer-test/image-info", line 2883, in <module>
    main()
...
osbuild.host.RemoteError: RuntimeError: b'mount: /tmp/tmp1mo2j31_/app: wrong fs type, bad option, bad superblock on /dev/mapper/rootvg-applv, missing codepage or helper program, or other error.\n       dmesg(1) may have more information after failed mount system call.' (code: 32)
```

2023-12-13 01:33 UTC, henrywang commented
All RHEL 8 and RHEL 9 failure is caused by ansible upgrade. The PR https://github.com/osbuild/osbuild-composer/pull/3845 fixed this issue. Could you please make a rebase? Thanks.

2023-12-18 04:44 UTC, henrywang commented
All edge-simplified test failure is not caused by this PR. Issue has been fixed by PR https://github.com/osbuild/osbuild-composer/pull/3854

2024-01-08 18:10 UTC, mvo5 commented
I logged into the system now and managed to get hold of the failing image. It looks like mount in fc39 is behaving differently, I can also reproduce this on an debian/unstable system. The issue happens when `image-info` calls `mount '-t', 'xfs', '-o', 'ro,norecovery', '--source', '/dev/rootvg/applv', '--target', '/tmp/tmpngmoxtqq/app'`. The jounrnal shows: `no-recovery mounts must be read-only`.

When I run the following:
```
$ dd if=/dev/zero of=/tmp/xfs.img bs=1M count=500
$ mkfs.xfs /tmp/xfs.img
$ sudo mount -o "ro,norecovery" /tmp/xfs.img /mnt
```
the mount fails. Doing the same for ext4:
```
$ dd if=/dev/zero of=/tmp/ext4.img bs=1M count=500
$ mkfs.ext4 /tmp/ext4.img
$ sudo mount -o ro,norecovery /tmp/ext4.img /mnt
```
works just fine.

However the strace output is different:
```
$ sudo strace mount -o ro,norecovery /tmp/xfs.img /mnt
...
fsopen("xfs", FSOPEN_CLOEXEC)           = 3
...
fsconfig(3, FSCONFIG_SET_STRING, "source", "/dev/loop1", 0) = 0
fsconfig(3, FSCONFIG_SET_FLAG, "ro", NULL, 0) = 0
fsconfig(3, FSCONFIG_SET_FLAG, "norecovery", NULL, 0) = 0
fsconfig(3, FSCONFIG_CMD_CREATE, NULL, NULL, 0) = -1 EINVAL (Invalid argument)
close(3)
```
which is fine on ext4:
```
fsopen("ext4", FSOPEN_CLOEXEC)          = 3
....
fsconfig(3, FSCONFIG_SET_STRING, "source", "/dev/loop0", 0) = 0
fsconfig(3, FSCONFIG_SET_FLAG, "ro", NULL, 0) = 0
fsconfig(3, FSCONFIG_SET_FLAG, "norecovery", NULL, 0) = 0
fsconfig(3, FSCONFIG_CMD_CREATE, NULL, NULL, 0) = 0
fsmount(3, FSMOUNT_CLOEXEC, 0)          = 5
```

Now if I compare this with fc38 strace there is just the "old" mount(2) syscall used and the output is essentially: `mount("/dev/loop0", "/mnt", "xfs", MS_RDONLY, "norecovery")`. So it looks like the support for the new mount syscalls in xfs is incomplete?

2024-01-08 19:52 UTC, mvo5 commented
This is an upstream patch on the xfs mailing list: https://lkml.kernel.org/linux-xfs/20230823220225.3591135-1-david@fromorbit.com/#t  but AFAICT this is not yet applied to Linus tree :/

2024-01-09 09:50 UTC, mvo5 commented on .gitlab-ci.yml
> +      - aws/fedora-38-x86_64
Would you mind expanding the comment to say why it's not run there yet? Maybe something like: 
```
# don't execute on fedora-39 yet until https://lkml.kernel.org/linux-xfs/20230823220225.3591135-1-david@fromorbit.com/#t is in the kernel
# see also https://github.com/osbuild/osbuild-composer/pull/3820#issuecomment-1881587335 for more details
```

2024-01-09 11:52 UTC, ondrejbudai approved these changes
Thanks!

2024-01-09 11:57 UTC, mvo5 approved these changes
This was a difficult one, thank you for your patience!

2024-01-09 16:49 UTC, achilleas-k approved these changes

2024-01-09 16:50 UTC, achilleas-k commented
> This was a difficult one, thank you for your patience!

Thank you SO MUCH for all the effort you put into this! :heart:

2024-01-09 16:56 UTC, achilleas-k commented
Comments addressed.
RHEL 9.4 nightly failures are being addressed in #3883.

We _can_ admin merge if we're in a real hurry to get this in, but it looks like the other PR should be passing soon too so maybe it can wait.

2024-01-10 08:40 UTC, thozza approved these changes

2024-01-10 14:47 UTC, merged