Adjust expected response based on osbuild-composer version
osbuild/osbuild-composer pull request #3858
Opened 2023-12-18 08:40 UTC by atodorov

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2023-12-18 09:08 UTC, jrusz submitted a review, later dismissed

2023-12-18 13:44 UTC, jrusz commented
For some reason the test is failing everywhere, but I don't see why.

2023-12-19 10:21 UTC, jrusz commented
I got curious and did some debugging and it seems that the offending line is:
```
 RESPONSE=$(sudo composer-cli blueprints push $TEST_BP 2>&1)
```
If I surround it with `set +e` and `set -e` the test seems to behave as expected. I guess this is because there are actually no `set` statements in the script but in the function `nvrGreaterOrEqual` there is `set -e` at the end and I guess that's why the first iteration works and the second one fails...

2023-12-19 10:22 UTC, atodorov commented
FTR from https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/5782461753

```
INFO: Start interating over ALL_REMAINDERS
INFO: iterating over centos-8
DEBUG: centos-8, RESPONSE=ERROR: BlueprintsError: 'centos-8' is not a valid distribution
Blueprint push with centos-8 distro failed as expected.
INFO: iterating over centos-9
96 < 97
```

From the log messages it's clear that the script dies somehwhere between these lines, on the second iteration of the for loop:
https://github.com/osbuild/osbuild-composer/pull/3858/files#diff-e027796660fd9f47f7b2a38bf7234860367c7ab6a4daf21f6a83fb749cd121e7R145-R159

which makes no sense to me at all :-(.

2023-12-19 10:52 UTC, jrusz commented
> FTR from https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/5782461753
> 
> ```
> INFO: Start interating over ALL_REMAINDERS
> INFO: iterating over centos-8
> DEBUG: centos-8, RESPONSE=ERROR: BlueprintsError: 'centos-8' is not a valid distribution
> Blueprint push with centos-8 distro failed as expected.
> INFO: iterating over centos-9
> 96 < 97
> ```
> 
> From the log messages it's clear that the script dies somehwhere between these lines, on the second iteration of the for loop: https://github.com/osbuild/osbuild-composer/pull/3858/files#diff-e027796660fd9f47f7b2a38bf7234860367c7ab6a4daf21f6a83fb749cd121e7R145-R159
> 
> which makes no sense to me at all :-(.

See my comment above, I think that explains it.

2023-12-19 11:26 UTC, atodorov commented
> If I surround it with `set +e` and `set -e` the test seems to behave as expected. 

Thanks for finding this out. 

> I guess this is because there are actually no `set` statements in the script but in the function `nvrGreaterOrEqual` there is `set -e` at the end and I guess that's why the first iteration works and the second one fails...

There's also a `set +e` inside the `nvrGreaterOrEqual` function so the trailing `set -e` is supposed to be doing its job. The answer here is not that we are missing an opening `set +e` statement.

Quick google search reveals that [calling set +/-e in this way may be unreliable](https://stackoverflow.com/questions/44014857/function-invocation-in-for-loop-does-not-fail-even-with-set-e)! I will redo the if condition and move it outside the loop because we don't need to evaluate it every single time. And I'm not really in the mood to debug the intricacies of Bash and find out when it works and when it doesn't!

2023-12-22 09:43 UTC, jrusz requested changes
Can you remove the debug commits? I don't think they need to be kept here.

2023-12-22 10:07 UTC, jrusz approved these changes

2023-12-22 10:07 UTC, merged