Update osbuild/image to <waiting on tag>
osbuild/osbuild-composer pull request #4007
Opened 2024-03-13 02:22 UTC by andremarianiello

Extend user customizations to include an expiration date. This allows users to be configured to require password change on first login.

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the READMEs [listed here](https://github.com/osbuild/osbuild.github.io/blob/main/readme-list)
  - [ ] submit a PR for the [osbuild.org website](https://github.com/osbuild/osbuild.github.io/) repository if this PR changed any behavior not covered by the automatically updated READMEs

2024-03-26 14:50 UTC, andremarianiello commented
osbuild/images got a tag with the necessary changes, so I have updated this PR to depend on that tag and I also made a doc change PR, so I think this is ready to go. Thanks!

2024-03-26 22:08 UTC, bcl requested changes
I looks like you accidentally squashed your commit into the image update commit, there's only one commit now.

2024-03-27 14:20 UTC, andremarianiello commented
> I looks like you accidentally squashed your commit into the image update commit, there's only one commit now.

This has been a single commit *I think* since I opened it. I think you may be thinking of my PR in osbuild/images that had a separate commit for the go fmt change, so I will do the same thing here.

2024-03-27 14:23 UTC, andremarianiello commented
Done. Go fmt changes to customizations_test.go are separated into their own commit.

2024-03-29 23:31 UTC, bcl requested changes
Ok, now I see 2 commits. But the one with the title 'Update osbuild/image to v0.51.0' isn't doing that. And the body of it says  it is doing things to user customizations when all it is doing is adding the field to the customizations test.  So the commit message on that one needs to be fixed.

2024-03-29 23:42 UTC, andremarianiello commented
> Ok, now I see 2 commits. But the one with the title 'Update osbuild/image to v0.51.0' isn't doing that. And the body of it says it is doing things to user customizations when all it is doing is adding the field to the customizations test. So the commit message on that one needs to be fixed.

A different PR that bumped osbuild/images up to v0.51.0 got merged already (1ce72071) and when I rebased the source branch of this PR on top of the target branch it eliminated 95% of the changes and only some inconsequential bits are left. If you still want the little bits that are left I can fix the commit messages. If you don't I can close it. What do you prefer?

2024-03-29 23:46 UTC, bcl commented
yeah, seems worthwhile to clean things up, thanks!

2024-04-01 13:44 UTC, andremarianiello commented
> yeah, seems worthwhile to clean things up, thanks!

Done!

2024-04-08 23:17 UTC, bcl approved these changes
Looks good, thanks!

2024-04-16 15:12 UTC, andremarianiello commented
Looks like some checks need to be rerun

2024-05-27 11:06 UTC, merged