worker: fix OSBUILD_SOURCES_CURL_SSL_CA_CERT variable
osbuild/osbuild-composer pull request #4423
Opened 2024-10-22 07:02 UTC by lzap

This looks like a copy and paste error.

The variable name was not correct:

https://github.com/osbuild/osbuild/blob/4b4b5cea950910ed9e1bc9d2fc1c618e0596b2b7/sources/org.osbuild.curl#L14

2024-10-22 07:20 UTC, supakeen requested changes
Why is this PR introducing a second environment variable that isn't used elsewhere? It's not mentioned in the title, description, or commit.

2024-10-22 07:32 UTC, lzap commented
Ah that was a leftover, I am working on this code in a different branch I was splitting git hunk. Fixed.

2024-10-22 07:32 UTC, supakeen approved these changes
Ok, thank you.

2024-10-22 09:17 UTC, achilleas-k approved these changes
Good catch.  How long has that been there?

Thanks!

2024-10-22 09:18 UTC, achilleas-k commented
Some testing would be nice for this.  Could you add one in a follow-up?

2024-10-22 13:17 UTC, lzap commented
Sure if you point me to the right place.

2024-10-24 08:03 UTC, lzap commented
How exactly I should be testing this? I just verified that this variable is properly used in `ostree` and I actually made a change that ensures it works properly:

https://github.com/osbuild/osbuild/pull/1910

This code only passes the variable into the worker, as long as there is no typo it will work. I believe the cert is enrolled at the OS level in `/etc/pki/ca-certs` thus `curl` gets it from there, that should explain why it worked until now.

2024-10-24 09:53 UTC, merged