worker: check MTLS config for ostree
osbuild/osbuild-composer pull request #4467
Opened 2024-11-08 17:04 UTC by lzap

My MTLS patch was not correctly checking MTLS config - it is currently missing and all builds are failing.

https://issues.redhat.com/browse/HMS-4975

2024-11-08 17:12 UTC, achilleas-k requested changes

2024-11-08 17:12 UTC, achilleas-k commented on cmd/osbuild-worker/jobimpl-ostree-resolve.go
> +	}
Should probably also check if BaseURL is nil.
```suggestion
	if job.RepositoryMTLSConfig == nil || job.RepositoryMTLSConfig.BaseURL == nil {
		return false, nil
	}
```

2024-11-08 17:12 UTC, achilleas-k commented on cmd/osbuild-worker/jobimpl-ostree-resolve.go
> +			if impl.RepositoryMTLSConfig != nil {
Same here.
```suggestion
			if impl.RepositoryMTLSConfig != nil && impl.RepositoryMTLSConfig.BaseURL != nil {
```

2024-11-08 18:30 UTC, lzap commented
Good catch, amended.

2024-11-11 10:36 UTC, achilleas-k requested changes

2024-11-11 10:36 UTC, achilleas-k commented on cmd/osbuild-worker/jobimpl-ostree-resolve.go
> +			if impl.RepositoryMTLSConfig != nil || impl.RepositoryMTLSConfig.BaseURL == nil {
Should be
```suggestion
			if impl.RepositoryMTLSConfig != nil || impl.RepositoryMTLSConfig.BaseURL != nil {
```

2024-11-11 12:30 UTC, lzap commented
Fixed, tests looking good.

2024-11-12 10:13 UTC, croissanne approved these changes
thanks for the fix!

2024-11-12 11:12 UTC, achilleas-k approved these changes

2024-11-12 11:12 UTC, merged