tests: Add option to fail qemu boot. Fix #888
osbuild/osbuild-composer pull request #961
Opened 2020-09-03 10:22 UTC by atodorov

as @teg suggests in
https://github.com/osbuild/osbuild-composer/issues/888#issuecomment-662942314
this is ON by default so we can be alerted for missing cloud
credentials in CI!

If you want to disable it then -fail-local-boot=off

2020-09-07 14:43 UTC, atodorov commented
> no AWS credentials given, falling back to booting using qemu

then fails with the new option

2020-09-14 12:49 UTC, ondrejbudai requested changes
Good idea but I find the change confusing. See my comment inline.

2020-09-14 12:49 UTC, ondrejbudai commented on cmd/osbuild-image-tests/main_test.go
> +func bootWithQemu(t *testing.T, imagePath string) {
I think this function name is kinda confusing. I suggest moving the condition to `testBootUsingVMware` and the other cloud-specific functions. That makes more sense to me.

2020-09-21 11:11 UTC, atodorov commented
@teg, @ondrejbudai ping?

2020-09-22 14:02 UTC, ondrejbudai approved these changes

2020-09-22 14:02 UTC, merged